#! /bin/sh
#
# ~/.xmonad/session Based on /etc/Xinit/xinitrc in Fedora dist.
#
# see also: /usr/bin/xmonad-start and /etc/Xinit/xinitrc
#

# Mandatorily source xinitrc-common, which is common code shared between the
# Xsession and xinitrc scripts which has been factored out to avoid duplication
source /etc/X11/xinit/xinitrc-common

trayer --edge top --align right --SetDockType true --SetPartialStrut false --expand true --transparent true --tint 0x000000 --alpha 255 --height 20 &
nm-applet --sm-disable &
ibus-daemon -r -x -d

## Done in /etc/X11/xinit/xinitrc-common:
#xmodmap -merge $HOME/.Xmodmap  # 

$CK_XINIT_SESSION $SSH_AGENT xmoand

