#! /bin/sh
#
# ~/.xmonad/session Based on /etc/Xinit/xinitrc in Fedora dist.
#
# see also: /usr/bin/xmonad-start and /etc/Xinit/xinitrc
#

# Mandatorily source xinitrc-common, which is common code shared between the
# Xsession and xinitrc scripts which has been factored out to avoid duplication
source /etc/X11/xinit/xinitrc-common

sleep 2

# This must be started before seahorse-daemon.
eval $(gnome-keyring-daemon)
export GNOME-KEYRING-SOCKET
export GNOME-KEYRING-PID

gnome-keyring-daemon --start
#export SSH_AUTH_SOCK="$GNOME_KEYRING_CONTROL/ssh"

#xcompmgr -c C -f -F &

GTK2_RC_FILES=/usr/share/themes/Paranoid/gtk-2.0/gtkrc trayer --edge top --align right --tint 0x000000 --height 22
#trayer --edge top --align right --transparent true --tint 0x000000 --height 20 --alpha 255 &

nm-applet --sm-disable &
ibus-daemon -r -x -d
xscreensaver &

## Done in /etc/X11/xinit/xinitrc-common:
#xmodmap -merge $HOME/.Xmodmap
#xrdb -merge $HOME/.Xresources
setxkbmap -option ctrl:nocaps

$CK_XINIT_SESSION $SSH_AGENT xmonad
