# cabal2spec-0.25
# https://fedoraproject.org/wiki/Packaging:Haskell
# https://fedoraproject.org/wiki/PackagingDrafts/Haskell

Name:           c2hs
Version:        0.16.3
Release:        1%{?dist}
Summary:        A interfacing tool that eases Haskell access to C libraries
Group:          Development/Tools
License:        GPLv2+
# BEGIN cabal2spec
URL:            http://hackage.haskell.org/package/%{name}
Source0:        http://hackage.haskell.org/packages/archive/%{name}/%{version}/%{name}-%{version}.tar.gz
ExclusiveArch:  %{ghc_arches}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# END cabal2spec
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-language-c-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-pretty-devel


%description
C->Haskell is a interfacing tool that eases Haskell access to C libraries.  The
tool gets information about the C data type definitions and function signatures
by analysing the C header files of the library.  It uses this information to
compute the missing details in the template of a Haskell module---called the
binding file---that implements a Haskell binding to the C library.  Hooks
embedded in the binding file signal where, which, and how C objects are
accessed from Haskell.  The Haskell code in the binding file determines Haskell
types signatures and marshaling details.


%prep
%setup -q


%build
%ghc_bin_build


%install
%ghc_bin_install


%files
%doc README LICENSE AUTHORS TODO
%attr(755,root,root) %{_bindir}/%{name}


%changelog
* Thu Jun  7 2012 Satoru SATOH <ssato@redhat.com>
- Added missing summary, description and other rpm meta data
- Added missing build-time dependencies
- Added docs

* Thu Jun  7 2012 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.5
