# cabal2spec-0.25.2
# https://fedoraproject.org/wiki/Packaging:Haskell
# https://fedoraproject.org/wiki/PackagingDrafts/Haskell

%global pkg_name hspec
#%%global common_summary Haskell %{pkg_name} library
#%%global common_description A %{pkg_name} library for Haskell.
%global common_summary Haskell %{pkg_name} library
%global common_description Behavior Driven Development library for Haskell


Name:           ghc-%{pkg_name}
Version:        0.9.0
Release:        0%{?dist}
Summary:        %{common_summary}
Group:          System Environment/Libraries
License:        BSD
# BEGIN cabal2spec
URL:            http://hackage.haskell.org/package/%{pkg_name}
Source0:        http://hackage.haskell.org/packages/archive/%{pkg_name}/%{version}/%{pkg_name}-%{version}.tar.gz
ExclusiveArch:  %{ghc_arches}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros %{!?without_hscolour:hscolour}
# END cabal2spec
BuildRequires:  ghc-HUnit-devel
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-silently-devel
BuildRequires:  ghc-ansi-terminal-devel
BuildRequires:  ghc-transformers-devel


%description
%{common_description}

Hspec is roughly based on the Ruby library RSpec. However, Hspec is just a
framework for running HUnit and QuickCheck tests. Compared to other options, it
provides a much nicer syntax that makes tests very easy to read.


%prep
%setup -q -n %{pkg_name}-%{version}


%build
%ghc_lib_build


%install
%ghc_lib_install


%ghc_devel_package

%ghc_devel_description


%ghc_devel_post_postun


%ghc_files


%changelog
* Sat Jan 21 2012 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.2
