# For Haskell Packaging Guidelines see:
# - https://fedoraproject.org/wiki/Packaging:Haskell
# - https://fedoraproject.org/wiki/PackagingDrafts/Haskell

%global pkg_name HStringTemplate
%global common_summary Haskell %{pkg_name} library
%global common_description HStringTemplate is a Haskell port of a Java template engine, StringTemplate.


Name:           ghc-%{pkg_name}
Version:        0.6.8
Release:        1%{?dist}
Summary:        %{common_summary}
Group:          System Environment/Libraries
License:        BSD
# BEGIN cabal2spec
URL:            http://hackage.haskell.org/package/%{pkg_name}
Source0:        http://hackage.haskell.org/packages/archive/%{pkg_name}/%{version}/%{pkg_name}-%{version}.tar.gz
ExclusiveArch:  %{ghc_arches}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros %{!?without_hscolour:hscolour}
# END cabal2spec
# BR any C devel dependency here
# list ghc-*-prof dependencies:
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-old-locale-devel
BuildRequires:  ghc-old-time-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-syb-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-utf8-string-devel
# for quasi-quotation flag:
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-mtl-devel
# for syb-with-class flag (syb-with-class is Not available in Fedora):
BuildRequires:  ghc-syb-with-class-devel


%description
%{common_description}


%prep
%setup -q -n %{pkg_name}-%{version}


%build
%define cabal_configure_options -f smaller-base -f quasi-quotation -f syb-with-class
%ghc_lib_build


%install
%ghc_lib_install


# devel subpackage
%ghc_devel_package

%ghc_devel_description

%ghc_devel_post_postun

%ghc_files LICENSE


%changelog
* Mon Jul  9 2012 Satoru SATOH <ssato@redhat.com> - 0.6.8-1
- New upstream release
- Enabled syb-with-class build flag

* Tue Jan 17 2012 Satoru SATOH <ssato@redhat.com> - 0.6.6-1
- Enabled smaller-base and quasi-quotation flags
- Added build time dependencies: ghc-template-haskell-devel and ghc-mtl-devel
- Fixed license

* Tue Jan 17 2012 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org> - 0.6.6-0
- initial packaging for Fedora automatically generated by cabal2spec-0.24.1
