# cabal2spec-0.25
# https://fedoraproject.org/wiki/Packaging:Haskell
# https://fedoraproject.org/wiki/PackagingDrafts/Haskell

%global pkg_name remote
%global common_summary Haskell %{pkg_name} library
%global common_description A %{pkg_name} library for Haskell.


Name:           ghc-%{pkg_name}
Version:        0.1.1
Release:        1%{?dist}
Summary:        %{common_summary}
Group:          System Environment/Libraries
License:        BSD
# BEGIN cabal2spec
URL:            http://hackage.haskell.org/package/%{pkg_name}
Source0:        http://hackage.haskell.org/packages/archive/%{pkg_name}/%{version}/%{pkg_name}-%{version}.tar.gz
ExclusiveArch:  %{ghc_arches}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros %{!?without_hscolour:hscolour}
# END cabal2spec
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-network-devel
BuildRequires:  ghc-syb-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-pureMD5-devel
BuildRequires:  ghc-utf8-string-devel
BuildRequires:  ghc-directory-devel


%description
%{common_description}


%prep
%setup -q -n %{pkg_name}-%{version}


%build
%ghc_lib_build


%install
%ghc_lib_install


# devel subpackage
%ghc_devel_package

%ghc_devel_description

%ghc_devel_post_postun

%ghc_files LICENSE


%changelog
* Fri Jul 13 2012 Satoru SATOH <ssato@redhat.com> - 0.1.1-1
- Added build-time depends

* Fri Jul 13 2012 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.5
